yolo_model:

  config_file:
    name: yolov3.cfg
  weight_file:
    name: yolov3.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - person
      - bench
      - bottle
      - wine glass
      - cup
      - bowl
      - orange
      - chair
      - sofa
      - bed
      - diningtable
      - refrigerator
